variables:
- name: ReleaseEnvironmentName
  value: dev-draft
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Banners
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-banners-draft
- name: ContentMode
  value: DRAFT
- name: contentUrl
  value: $(ContentApiDraftAddress)/api/execute
- name: apiName
  value: banners-draft
- name: apiId
  value: composite-ui-banners-draft
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-dev-draft-app-banners
- name: EnableAzureMonitorAlerting
  value: true
- name: clientAffinity
  value: false
- name: appDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: LoggingLogLevelDefault
  value: Trace
- name: Expiry
  value: 4
- name: SubscriptionPosturi
  value: https://$(AppServiceName).$(AppServiceDomain)/subscription/