variables:
- name: ReleaseEnvironmentName
  value: lab
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: cosmosDBCollectionName
  value: banners
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Banners
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-banners
- name: ContentMode
  value: PUBLISHED
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-lab-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/banners
- name: apiName
  value: banners
- name: apiId
  value: composite-ui-banners
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-lab-app-banners
- name: SubscriptionSettingsFilterIncludeEventTypes3
  value:
- name: SubscriptionSettingsFilterIncludeEventTypes4
  value:
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
  value: /content/banner/
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values1
  value: /content/pagebanner/
- name: EnableAzureMonitorAlerting
  value: true
- name: clientAffinity
  value: false
- name: appDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: SubscriptionPosturi
  value: https://$(AppServiceName).$(AppServiceDomain)/subscription/
- name: LoggingLogLevelDefault
  value: Trace