variables:
- name: ReleaseEnvironmentName
  value: pp-draft
- name: AppServiceName
  value: $(WebAppPrefix)-as-ver2
- name: AppServicePlanSuffix
  value: -migrated
- name: cosmosDBCollectionName
  value: banners-draft
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Banners
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-banners-draft
- name: ContentMode
  value: DRAFT
- name: contentUrl
  value: $(ContentApiDraftAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-pp-api-eventgridsubscriptions-fa-ver2.$(appServiceDomain)
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/banners-draft
- name: apiName
  value: banners-draft
- name: apiId
  value: composite-ui-banners-draft
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-pp-draft-app-banners
- name: SubscriptionSettingsFilterIncludeEventTypes3
  value: draft-discarded
- name: SubscriptionSettingsFilterIncludeEventTypes4
  value: draft
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values0
  value: /content/banner/
- name: SubscriptionSettingsFilterPropertyContainsFilters0Values1
  value: /content/pagebanner/
- name: EnableAzureMonitorAlerting
  value: true
- name: clientAffinity
  value: false
- name: appDatabaseThroughput
  value: 5000
- name: ExceptionCountThreshold
  value: 10
- name: SubscriptionPosturi
  value: https://$(AppServiceName).$(AppServiceDomain)/subscription/
- name: LoggingLogLevelDefault
  value: Warning