variables:
- name: ReleaseEnvironmentName
  value: pp
- name: AppServiceName
  value: $(WebAppPrefix)-as-ver2
- name: AppServicePlanSuffix
  value: -migrated
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Banners
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-banners
- name: ContentMode
  value: PUBLISHED
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-pp-api-eventgridsubscriptions-fa-ver2.$(appServiceDomain)
- name: apiName
  value: banners
- name: apiId
  value: composite-ui-banners
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-pp-app-banners
- name: EnableAzureMonitorAlerting
  value: true
- name: clientAffinity
  value: false
- name: appDatabaseThroughput
  value: 5000
- name: ExceptionCountThreshold
  value: 10
- name: LoggingLogLevelDefault
  value: Warning
- name: Expiry
  value: 4
- name: SubscriptionPosturi
  value: https://$(AppServiceName).$(AppServiceDomain)/subscription/
