variables:
- name: ReleaseEnvironmentName
  value: sit
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Banners
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: dfc-app-banners
- name: ContentMode
  value: PUBLISHED
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: apiName
  value: banners
- name: apiId
  value: composite-ui-banners
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-sit-app-banners
- name: EnableAzureMonitorAlerting
  value: true
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: clientAffinity
  value: false
- name: appDatabaseThroughput
  value: 400
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: LoggingLogLevelDefault
  value: Trace 
- name: Expiry
  value: 4 